config/routes.rb
Rails.application.routes.draw do

  resources :organizations, only: [:new, :show, :index, :create]
  get 'sessions/new'

  root 'welcome#landing'

  resources :users do 
  	resources :followers
    resources :uploads, only: [:new, :create, :index, :destroy, :show]
  end

  resources :users, only: [:new, :create,:edit,:update,:destroy]

  get '/notes/new', :to => 'notes#new', :as => :new_note
  get '/notes/:id', :to => 'notes#show', :as => :notes
  post '/notes/new', :to => 'notes#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower <ApplicationRecord
	belongs_to :organization
	belongs_to :organizer, class_name: 'User'
	has_many :notes, as: :notable
	has_many :taggings, :as => :taggable
	has_many :tags, through: :taggings
	validates_presence_of :first_name, :last_name

	attr_reader :tag_ids

	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


	def full_name
		first_name + " " + last_name
	end

	def ggl_address
		self.street_number.nil? ? "#{self.longitude},#{self.latitude}" : Follower.to_ggl_api_address(self.address) #refactor
	end

	def self.to_ggl_api_address(addr)
		addr.gsub(" ","+")
	end

	def add_tags(ids)
		ids.each do |id|
			next if id == ""
			Tagging.create!(taggable_type:'Follower',taggable_id:self.id,tag_id:id.to_i)
		end
	end

end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :user
	belongs_to :organization
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :notable, polymorphic:true
	belongs_to :author, class_name: 'User'
	has_many :taggings, :as => :taggable
	has_many :tags, through: :taggings

	def toNoteDiv
		"<div class='follower-note'>
			<span class='note-text'>#{self.info}</span>
			<br>
			" + tagDivs + "<h7> Added #{self.created_at unless self.created_at.nil?} </h7>
			</div>"
	end

	def tagDivs
		str = ""
		self.tags.each do |tag|
			str += "<div class='tagDiv'> #{tag.name} </div>"
		end
		str
	end

	def add_tags(ids)
		ids.first.split(",").map(&:to_i).each do |id|
			next if id == ""
			Tagging.create!(taggable_type:'Note',taggable_id:self.id,tag_id:id.to_i)
		end
	end

end

app/models/organization.rb
class Organization < ApplicationRecord

	has_many :memberships
	has_many :leaders, through: :memberships, :source => :user
	has_many :members, class_name: 'Follower'
	has_many :notes, as: :notable
	validates :name, length: {minimum: 3}
	has_many :tags, as: :taggable
	has_many :uploads, foreign_key:'organization_id'
	has_many :terfs, class_name:'Terf'
	
	EMAIL_REGEX = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/

	validates :website, format: {with: EMAIL_REGEX , on: :create}, :allow_blank => true



end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings	
	belongs_to :taggable, polymorphic: true, optional:true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
	belongs_to :tag
end

app/models/terf.rb
class Terf < ApplicationRecord

	belongs_to :organization
	has_many :terf_entries
	belongs_to :upload

end

app/models/terf_entry.rb
class TerfEntry < ApplicationRecord
	belongs_to :terf
end

app/models/upload.rb
class Upload < ApplicationRecord
	require 'csv'
	belongs_to :uploader, class_name: 'User'
	belongs_to :organization

	def self.generateTerf(upload,affiliate_id,file,upload_id=nil)
		t = Terf.create(organization_id:affiliate_id,upload_id:upload_id)
		CSV.foreach(file.tempfile,headers:false) do |row|
			street_num,street_name = row[2].match(/(\d+-?\d?+)(.*)/)[1,2]
			TerfEntry.create(first_name:row[0],last_name:row[1],street_number:street_num,street_name:street_name.strip,city:row[3],state:row[4],zip:row[5],county:row[6],terf_id:t.id)
		end
	end
end


# rpatel@brooksource.com 

app/models/user.rb
class User < ApplicationRecord
	has_many :memberships
	has_many :affiliations, :through => :memberships, :source => :organization
	has_many :followers, :foreign_key => :organizer_id
	has_many :uploads, foreign_key:'uploader_id'
	
	has_secure_password

	validates_presence_of :first_name, :last_name, :email, :password_digest

	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

	validates :first_name, length: {minimum:2}

	validates :email, uniqueness: true

	def full_name
		first_name + " " + last_name
	end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	protect_from_forgery with: :null_session

	def new
		@note = Note.new
	end

	def create
		@note = Note.new(notes_params)

		if @note.save 
			respond_to do |format|
				@note.add_tags(params["note"]["tag_ids"])
				format.json {render head:"ok", json:{data:@note.toNoteDiv}} #refactor?
				format.html { root_path }
			end
		else 
			respond_to do |format| 
				format.json {render json: @note.errors, status: :unprocessable_entity}
			end
		end

	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		@note.update_attributes!(notes_params)
	end

	def destroy
	end

	private

	def notes_params
		params.require(:note).permit(:author_id,:notable_type,:notable_id,:info,:tag_ids)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

	def create
	  user = User.find_by(email: params[:session][:email])
	  if user && user.authenticate(params[:session][:password])
	  	puts "VALID LOGIN"
	    log_in(user)
	    redirect_to user_path(user.id), notice: 'Logged in!'
	  else
	  	puts "INVALID LOGIN"
	    flash[:danger] = 'Invalid email/password combination'
	    render :new
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: 'Logged out!'
	end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new #refactor -- is this neccessary?
  end

  def create
    secure_id = SecureRandom.uuid
    file = upload_params[:file]
    resp = S3_BUCKET.object(secure_id).upload_file(file.tempfile)

    if resp #refactor
      upload = Upload.create!(name:file.original_filename,
        uploader_id:current_user.id,
        s3_id:secure_id,
        organization_id:upload_params[:organization_id]
      )
      Upload.generateTerf(upload,upload_params[:organization_id],file,upload.id)
      redirect_to user_uploads_path(user_id:current_user.id, id:upload.id)
    else
      flash.now[:notice] = 'There was an error'
      render :new
    end
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def index
    @uploads = current_user.uploads
  end

  def destroy
  end

  private

  def upload_params
    params.require(:upload).permit(:file,:uploader_id,:organization_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def create
		@user = User.new(user_params)
		if @user.valid?
			@user.save
			ids = params[:user][:affiliation_ids][1..-1]
			ids.each {|id| Membership.create!(user_id:@user.id,organization_id:id.to_i)}
			redirect_to @user
		else
			render :new
		end
	end

	def new
		@user = User.new
	end

	def edit
		redirect_to root_path if !relevant_user?
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render :edit
		end
	end

	def show
		redirect_to root_path if !relevant_user?
		@user = User.find(params[:id])
	end

	def destroy
	end

	private

	def user_params
		params.require(:user).permit(:first_name,:last_name,:email,:affiliation,:password, :password_confirmation)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def landing
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/uploads/destroy.html.erb
<h1>Uploads#destroy</h1>
<p>Find me in app/views/uploads/destroy.html.erb</p>

app/views/uploads/index.html.erb
Here are your uploads..

<div class="upload_list">

	<% @uploads.each do |upload| %>
		<div class="upload_item" >
			<%= upload.name %>
		</div>
	<%end%>
</div>

app/views/uploads/new.html.erb
<h1>Upload a file</h1>

<%= simple_form_for @upload, :url => user_uploads_path(current_user.id), :multipart => :true, :method => :post do |f| %>
	<%= f.input :file, as: :file %>
	<%= f.hidden_field :uploader_id, value:current_user.id %>
	<%= f.input :organization_id, as: :radio_buttons, collection: current_user.affiliations.order(:name) %>
	<%= submit_tag 'Upload file' %>
<% end %>

app/views/users/_form.html.erb
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email %>
	<%= f.association :affiliations, as: :check_boxes, collection: Organization.order(:name) %>
	<%= f.input :password %>
	<%= f.input :password_confirmation%>

	<%= f.button :submit %>

app/views/users/_partial.html.erb
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email %>
	<%= f.association :affiliations, as: :check_boxes, collection: Organization.order(:name) %>
	<%= f.input :password %>
	<%= f.input :password_confirmation%>

	<%= f.button :submit %>

app/views/users/edit.html.erb
<h3>Edit your profile!</h3>

<%= simple_form_for @user do |f| %>
	<%= render partial:'form', locals:{:f => f} %>
	<% end %>

<h3>* denotes required field</h3>

app/views/users/index.html.erb
<h2>Here are all the users!</h2>

<ul>
	<% @users.each do |user|  %>
		<li><%= link_to user.full_name, user_path(user.id) %>
		</li>
	<% end %>
	
</ul>


<h2>Don't see yourself here? Click <a href="/users/new">here</a> to make a profile!</h2>

app/views/users/new.html.erb
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= simple_form_for @user do |f| %>
  <%= render partial:'form', locals:{:f => f} %>
<% end %>

<h3>* denotes required field</h3>

app/views/users/show.html.erb
<h2><%= link_to 'Go back to users', users_path%></h2>

<h3><%=@user.full_name%></h3>

<div id="user_upload_box">
	<span class="upload_link"><%= link_to 'Upload something', new_user_upload_path(current_user)%></span>
	<span class="user_uploads"><%= link_to 'View Uploads', user_uploads_path(current_user)%></span>
</div>

<div class="userMemberships">
	<span><%= relevant_user? ? "You" : "They" %> belong to...</span>
	<ul class="memberList">
		<% @user.affiliations.each do |mem| %>
			<%= link_to mem.name, organization_path(mem.id)%>
		<% end %>
	</ul>
</div>

<h4>Click <%= link_to 'here', edit_user_path(@user)%> to edit</h4>
<h4>Click <%= link_to 'here', new_user_follower_path(@user), class:'link'%> to create a follower!</h4>

<div class="followerListDiv">
	<div class="orgList">
		<div class="orgName org0">All Members</div>
		<% Organization.all.each do |org| %>
			<div class="orgName <%='org'+org.id.to_s%>"><%= org.name%></div>
		<% end %>
	</div>
		<ul class="followerList">
			<%current_user.followers.each do |follower| %>
				<li class="followerLi followerShow <%= 'org'+follower.organization_id %>"> <%= link_to follower.full_name, user_follower_path(current_user.id,follower.id)%> (<%= follower.organization.name%>) </li>
			<%end%>
		</ul>
</div>