config/routes.rb
Rails.application.routes.draw do

  resources :organizations, only: [:new, :show, :index, :create]
  get 'sessions/new'

  root 'welcome#landing'

  resources :users do 
  	resources :followers
    resources :uploads, only: [:new, :create, :index, :destroy, :show]
  end

  resources :users, only: [:new, :create,:edit,:update,:destroy]

  get '/notes/new', :to => 'notes#new', :as => :new_note
  get '/notes/:id', :to => 'notes#show', :as => :notes
  post '/notes/new', :to => 'notes#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower <ApplicationRecord
	belongs_to :organization
	belongs_to :organizer, class_name: 'User'
	has_many :notes, as: :notable
	has_many :taggings, :as => :taggable
	has_many :tags, through: :taggings
	validates_presence_of :first_name, :last_name

	attr_reader :tag_ids

	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


	def full_name
		first_name + " " + last_name
	end

	def ggl_address
		self.street_number.nil? ? "#{self.longitude},#{self.latitude}" : Follower.to_ggl_api_address(self.address) #refactor
	end

	def self.to_ggl_api_address(addr)
		addr.gsub(" ","+")
	end

	def add_tags(ids)
		ids.each do |id|
			next if id == ""
			Tagging.create!(taggable_type:'Follower',taggable_id:self.id,tag_id:id.to_i)
		end
	end

end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :user
	belongs_to :organization
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :notable, polymorphic:true
	belongs_to :author, class_name: 'User'
	has_many :taggings, :as => :taggable
	has_many :tags, through: :taggings

	def toNoteDiv
		"<div class='follower-note'>
			<span class='note-text'>#{self.info}</span>
			<br>
			" + tagDivs + "<h7> Added #{self.created_at unless self.created_at.nil?} </h7>
			</div>"
	end

	def tagDivs
		str = ""
		self.tags.each do |tag|
			str += "<div class='tagDiv'> #{tag.name} </div>"
		end
		str
	end

	def add_tags(ids)
		ids.first.split(",").map(&:to_i).each do |id|
			next if id == ""
			Tagging.create!(taggable_type:'Note',taggable_id:self.id,tag_id:id.to_i)
		end
	end

end

app/models/organization.rb
class Organization < ApplicationRecord

	has_many :memberships
	has_many :leaders, through: :memberships, :source => :user
	has_many :members, class_name: 'Follower'
	has_many :notes, as: :notable
	validates :name, length: {minimum: 3}
	has_many :tags, as: :taggable
	has_many :uploads, foreign_key:'organization_id'
	has_many :terfs, class_name:'Terf'
	
	EMAIL_REGEX = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/

	validates :website, format: {with: EMAIL_REGEX , on: :create}, :allow_blank => true



end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings	
	belongs_to :taggable, polymorphic: true, optional:true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
	belongs_to :tag
end

app/models/terf.rb
class Terf < ApplicationRecord

	belongs_to :organization
	has_many :terf_entries
	belongs_to :upload

end

app/models/terf_entry.rb
class TerfEntry < ApplicationRecord
	belongs_to :terf
end

app/models/upload.rb
class Upload < ApplicationRecord
	require 'csv'
	belongs_to :uploader, class_name: 'User'
	belongs_to :organization

	def self.generateTerf(upload,affiliate_id,file,upload_id=nil)
		t = Terf.create(organization_id:affiliate_id,upload_id:upload_id)
		CSV.foreach(file.tempfile,headers:false) do |row|
			street_num,street_name = row[2].match(/(\d+-?\d?+)(.*)/)[1,2]
			TerfEntry.create(first_name:row[0],last_name:row[1],street_number:street_num,street_name:street_name.strip,city:row[3],state:row[4],zip:row[5],county:row[6],terf_id:t.id)
		end
	end
end


# rpatel@brooksource.com 

app/models/user.rb
class User < ApplicationRecord
	has_many :memberships
	has_many :affiliations, :through => :memberships, :source => :organization
	has_many :followers, :foreign_key => :organizer_id
	has_many :uploads, foreign_key:'uploader_id'
	
	has_secure_password

	validates_presence_of :first_name, :last_name, :email, :password_digest

	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

	validates :first_name, length: {minimum:2}

	validates :email, uniqueness: true

	def full_name
		first_name + " " + last_name
	end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

	def new
		redirect_to root_path if !relevant_user?
		@follower = Follower.new
	end

	def create
		@follower = Follower.new(follower_params)
		if @follower.valid?
			@follower.save
			@follower.add_tags(params["follower"]["tag_ids"]) #refactor
			redirect_to user_path(current_user.id)
		else
			render :new
		end
	end

	def edit
		if !relevant_user?
			redirect_to root_path
		end
	end

	def show
		redirect_to root_path if !relevant_user?
		@follower = Follower.where(id:params[:id])[0]
		@notes = Note.where(author_id:@follower.id)
		@note = Note.new
	end

	def update
	end

	def destroy
	end


	private 

	def follower_params
		params.require(:follower).permit(:first_name,:last_name,
		:phone,:email,:organizer_id,:organization_id,
		:address, :longitude, :latitude, :zip,
		:street_number, :street_name,
		:city, :neighborhood, :state,:tag_ids)
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	protect_from_forgery with: :null_session

	def new
		@note = Note.new
	end

	def create
		@note = Note.new(notes_params)

		if @note.save 
			respond_to do |format|
				@note.add_tags(params["note"]["tag_ids"])
				format.json {render head:"ok", json:{data:@note.toNoteDiv}} #refactor?
				format.html { root_path }
			end
		else 
			respond_to do |format| 
				format.json {render json: @note.errors, status: :unprocessable_entity}
			end
		end

	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		@note.update_attributes!(notes_params)
	end

	def destroy
	end

	private

	def notes_params
		params.require(:note).permit(:author_id,:notable_type,:notable_id,:info,:tag_ids)
	end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new #refactor -- is this neccessary?
  end

  def create
    secure_id = SecureRandom.uuid
    file = upload_params[:file]
    resp = S3_BUCKET.object(secure_id).upload_file(file.tempfile)

    if resp #refactor
      upload = Upload.create!(name:file.original_filename,
        uploader_id:current_user.id,
        s3_id:secure_id,
        organization_id:upload_params[:organization_id]
      )
      Upload.generateTerf(upload,upload_params[:organization_id],file,upload.id)
      redirect_to user_uploads_path(user_id:current_user.id, id:upload.id)
    else
      flash.now[:notice] = 'There was an error'
      render :new
    end
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def index
    @uploads = current_user.uploads
  end

  def destroy
  end

  private

  def upload_params
    params.require(:upload).permit(:file,:uploader_id,:organization_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def create
		@user = User.new(user_params)
		if @user.valid?
			@user.save
			ids = params[:user][:affiliation_ids][1..-1]
			ids.each {|id| Membership.create!(user_id:@user.id,organization_id:id.to_i)}
			redirect_to @user
		else
			render :new
		end
	end

	def new
		@user = User.new
	end

	def edit
		redirect_to root_path if !relevant_user?
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render :edit
		end
	end

	def show
		redirect_to root_path if !relevant_user?
		@user = User.find(params[:id])
	end

	def destroy
	end

	private

	def user_params
		params.require(:user).permit(:first_name,:last_name,:email,:affiliation,:password, :password_confirmation)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def landing
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/followers/_initJs.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GGL_API_KEY']%>&libraries=places&callback=initAutocomplete" async defer></script>

app/views/followers/new.html.erb
<% if @follower.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% @follower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= simple_form_for [current_user,@follower] do |f| %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email %>
	<%= f.input :phone %>
	<%= f.association :organization, as: :radio_buttons,collection: Organization.order(:name) %>
  <%= f.input :tag_ids, as: :check_boxes, collection: Tag.order(:name) %>
  <%= f.input :address, input_html: {id:"gmaps-input-address", placeholder:"Address goes here.."} %>
  <%= f.hidden_field :street_number, value:''%>
  <%= f.hidden_field :street_name, value:''%>
  <%= f.hidden_field :neighborhood, value:''%>
  <%= f.hidden_field :city , value:''%>
  <%= f.hidden_field :county , value:''%>
  <%= f.hidden_field :state , value:''%>
  <%= f.hidden_field :zip , value:''%>
  <%= f.hidden_field :latitude, value:''%>
  <%= f.hidden_field :longitude, value:''%>
	<%= f.hidden_field :organizer_id, value: current_user.id%>
	<%= f.button :submit %>
<% end %>

<%= render 'initJs' %>

app/views/followers/show.html.erb
<h1>Name:<%= @follower.full_name %></h1>
<h2>Organization:<%= @follower.organization.name%></h2>

<div id="followerInfo">
	<h3><%= @follower.full_name %> was added <%= time_ago_in_words(@follower.created_at)%>. </h3>
	<span class="follower-address">Address:<%=@follower.address%> </span>
</div>

<div id="followerTags">
	<h3>Tags:</h3>
	<% @follower.tags.each do |tag| %>
		<div><%= tag.name %></div>
	<% end %>
</div>


<div id="followerMap">
	<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/search?q=<%=@follower.ggl_address%>&key=AIzaSyAqLbuWncCtGnuL-pIbRGx6I44fQlIGGwE&zoom=14" allowfullscreen>
	</iframe>
</div>


<div id="follower-notes">
	<h3>Existing Notes:</h3>
	<%@follower.notes.each do |note| %>
		<div class="follower-note"> 
			<span class="note-text"> <%=note.info%></span>
			<br> 
			<% note.tags.each do |tag| %>
				<div class='tagDiv'> <%= tag.name %> </div>
			<% end %>
			<h5>Added <%= time_ago_in_words(note.created_at) unless note.created_at.nil?%></h5>
		</div>
	<% end %>
</div>


<div id="new-note-form">
	<h4>Add a note...</h4>
	<%= simple_form_for @note, url: new_note_path(@note), remote:true do |f| %>
		<%= f.input :info, placeholder:'Write your note...' %>
		<%= f.hidden_field :notable_type, value:'Follower'%>
		<%= f.input :tag_ids, as: :check_boxes, collection: Tag.order(:name) %>
		<%= f.hidden_field :notable_id, value:params[:id]%>
		<%= f.hidden_field :author_id, value: current_user.id%>
		<%= f.button :submit, id:'submit-f-note' %>
	<% end %>
</div>